unbind C-b 
set-option -g prefix C-v
bind-key C-v send-prefix

# Config: quick reload
bind r source-file ~/.tmux.conf

# Mouse
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"

# Bell
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Statusbar
set -g status-position bottom
set -g status-justify left
set -g status-right-length 50
set -g status-left-length 20
