import = [
	"~/.config/alacritty/themes/catppuccin-mocha.toml",
]

shell = "/bin/zsh"
live_config_reload = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
padding = { x = 4, y = 10}
dynamic_padding = true
decorations = "Buttonless"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 15

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Off" }

[terminal]
osc52 = "CopyPaste"

