[env]
TERM = "screen-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
padding = { x = 4, y = 32}
dynamic_padding = true
decorations = "Transparent"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16

[colors.primary]
foreground = "#cdd6f4"
background = "#11111a"

