"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
command_timeout = 10000
palette = "catppuccin_mocha"
format = "$directory( $git_branch( $git_commit$git_state$git_metrics$git_status))( via (($golang )($nodejs )($lua )($c )($cmake )($python )($php )($swift )($docker_context )))$fill$cmd_duration$status\n\r"

[fill]
symbol = " "

[cmd_duration]
format = "[$duration]($style)"
min_time = 0
show_milliseconds = false
style = "yellow"

[status]
disabled = false
symbol = " (red)"
success_symbol = " (green)"
format = " $symbol"

[character]
format = "$symbol "
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"

[username]
format = "[$user]($style) in"
style_root = "bold red"
style_user = "bold yellow"
show_always = false

[git_branch]
symbol = " "
format = "on [$symbol$branch(:$remote_branch)]($style)"
style = "bold purple"
disabled = false

[git_commit]
disabled = false

[git_state]
disabled = false

[git_metrics]
disabled = false

[git_status]
disabled = false

[c]
symbol = " "
format = "[$symbol($version(-$name))]($style)"
style = "bold 149"
disabled = false

[cmake]
symbol = " "
format = "[$symbol($version)]($style)"
style = "bold blue"
disabled = false

[docker_context]
symbol = "  "
format = "[$symbol$context]($style)"
style = "bold blue"
disabled = false

[golang]
symbol = " "
format = "[$symbol($version)($mod_version)]($style)"
style = "bold cyan"
disabled = false

[lua]
symbol = " "
format = "[$symbol($version )]($style)"
style = "bold blue"
disabled = false

[nodejs]
symbol = " "
format = "[$symbol($version)]($style)"
style = "bold green"
disabled = false

[php]
symbol = " "
format = "[$symbol($version )]($style)"
style = "bold 147"
disabled = false

[python]
symbol = " "
format = "[${symbol}${pyenv_prefix}(${version})($virtualenv)]($style)"
style = "bold yellow"
disabled = false

[rust]
symbol = " "
format = "[$symbol($version )]($style)"
style = "bold red"
disabled = false

[swift]
symbol = " "
format = "[$symbol($version)]($style)"
style = "bold 202"
disabled = false

[shell]
symbol = ""
format = "[$indicator]($style)"
style = "bold white"
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
